version: '3.8'

services:

  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - diploma_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 15
    restart: always


  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    restart: always


  collect_static:
    build:
      context: .
      target: dev_image
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
      - ./core:/opt/core
      - ./goals:/opt/goals
      - ./bot:/opt/bot
    command: python3 manage.py collectstatic -c --no-input


  api:
    build:
      context: .
      target: dev_image
    env_file: .env
    environment:
      POSTGRES_HOST: db
#      DEBUG: "false"
    volumes:
      - ./todolist:/opt/todolist
      - ./core:/opt/core
      - ./goals:/opt/goals
      - ./bot:/opt/bot
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always


#  bot:
#    build:
#      context: .
#      target: dev_image
#    env_file: .env
#    volumes:
#      - ./bot:/opt/bot
##      - ./bot:/opt/bot/storage
##      - ./bot/logs:/opt/bot/logs
#      - ./core:/opt/core
#      - ./goals:/opt/goals
#      - ./todolist:/opt/todolist
##      - diploma_postgres_data:/var/lib/postgresql/data
##      - ./manage.py:/opt
#    depends_on:
#      db:
#        condition: service_healthy
#      api:
#        condition: service_started
#    restart: always
#    command: python3 manage.py runbot

#    command: python3 opt/bot/runbot.py
#
#
#  bot:
#    build:
#      context: .
#      target: prod_image
#    env_file: .env
#    volumes:
#      - ./bot:/opt/bot
##      - ./bot:/opt/bot/storage
##      - ./bot/logs:/opt/bot/logs
##      - ./core:/opt/core
##      - ./goals:/opt/goals
##      - ./todolist:/opt/todolist
#    depends_on:
#      db:
#        condition: service_healthy
#      api:
#        condition: service_started
#    restart: always
#    command: python3 manage.py runbot
##    command: python3 opt/bot/runbot.py

volumes:
  diploma_postgres_data:
  django_static:
