# Generated by Django 4.0.1 on 2023-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='comments',
            field=models.ManyToManyField(related_name='goal_w_comments', to='goals.GoalComment'),
        ),
    ]
