# Generated by Django 4.0.1 on 2023-02-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
