# Generated by Django 4.0.1 on 2023-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_category_alter_goal_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_for_goal', to='goals.GoalComment'),
        ),
    ]
