# Generated by Django 4.0.1 on 2023-02-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goal_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='comments',
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_comment', to='goals.goal', verbose_name='Цель'),
        ),
    ]
