# Generated by Django 4.0.1 on 2023-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='tg_user_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_user_phone',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, unique=True, verbose_name='Пользователь Телеграм'),
        ),
    ]
