# Generated by Django 4.0.1 on 2023-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_tguser_tg_user_id_tguser_tg_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='tg_user_phone',
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='Пользователь Телеграм'),
        ),
    ]
