# Generated by Django 4.0.1 on 2023-03-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_tguser_tg_user_phone_tguser_tg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='db_user',
            new_name='user',
        ),
    ]
